version: '3'

services:
  dump1090:
    restart: always
    build: .
    image: dump1090
    devices:
      - /dev/bus/usb
    tmpfs: /var/lib/dump1090/public_html/data     # uid=1000,gid=1000
    expose:
      - 8080    # HTTP server port
      - 8754    # fr24 dashboard port
      - 30001   # Raw output listen port
      - 30002   # Feed Dump1090 input listen port
      - 30003   # TCP BaseStation output listen port
      - 30004   # TCP Beast input listen port
      - 30005   # TCP Beast output listen port
      - 30104
    ports:
      - "8080:8080"   # HTTP server port
      - "8754:8754"   # fr24 dashboard port
  
