version: '3'

services:
  dump1090:
    image: dump1090
    container_name: dump1090
    restart: always
    build: .
    devices:
      - /dev/bus/usb
    tmpfs: /var/lib/dump1090/public_html/data     # uid=1000,gid=1000
    expose:
      - 8080    # HTTP server port
      - 8754    # fr24 dashboard port
      - 30001   # Raw output listen port
      - 30002   # Feed Dump1090 input listen port
      - 30003   # TCP BaseStation output listen port
      - 30004   # TCP Beast input listen port
      - 30005   # TCP Beast output listen port
      - 30104
    ports:
      - "127.0.0.1:30001-30005:30001-30005"    # data ports
      - "127.0.0.1:8753:8080"   # HTTP server port
      - "127.0.0.1:8754:8754"   # fr24 dashboard port
